defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true


# set these environment variables on your prod server
production:
  # Dummy URI is necessary for rake assets:precompile on Heroku since
  # environment variables are not available during the compiliation.
  uri: <%= ENV['MONGOLAB_URI'] || 'scheme://user:pass@127.0.0.1/dbname' %>

development:
  host: localhost
  database: roomies_development
  autocreate_indexes: true

test:
  host: localhost
  database: roomies_test>
