defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOID_URL'] %>

development:
  <<: *defaults
  database: roomies_development

test:
  <<: *defaults
  database: roomies_test>
