defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true


# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>

development:
  host: localhost
  database: roomies_development
  autocreate_indexes: true

test:
  host: localhost
  database: roomies_test>
