require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HouseInvitationsController
 do

  def mock_house_invitation(stubs={})
    @mock_house_invitation ||= mock_model(HouseInvitation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all house_invitations as @house_invitations" do
      HouseInvitation.stub(:all) { [mock_house_invitation] }
      get :index
      assigns(:house_invitations).should eq([mock_house_invitation])
    end
  end

  describe "GET show" do
    it "assigns the requested house_invitation as @house_invitation" do
      HouseInvitation.stub(:find).with("37") { mock_house_invitation }
      get :show, :id => "37"
      assigns(:house_invitation).should be(mock_house_invitation)
    end
  end

  describe "GET new" do
    it "assigns a new house_invitation as @house_invitation" do
      HouseInvitation.stub(:new) { mock_house_invitation }
      get :new
      assigns(:house_invitation).should be(mock_house_invitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested house_invitation as @house_invitation" do
      HouseInvitation.stub(:find).with("37") { mock_house_invitation }
      get :edit, :id => "37"
      assigns(:house_invitation).should be(mock_house_invitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created house_invitation as @house_invitation" do
        HouseInvitation.stub(:new).with({'these' => 'params'}) { mock_house_invitation(:save => true) }
        post :create, :house_invitation => {'these' => 'params'}
        assigns(:house_invitation).should be(mock_house_invitation)
      end

      it "redirects to the created invitation" do
        HouseInvitation.stub(:new) { mock_house_invitation(:save => true) }
        post :create, :house_invitation => {}
        response.should redirect_to(invitation_url(mock_house_invitation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved house_invitation as @house_invitation" do
        HouseInvitation.stub(:new).with({'these' => 'params'}) { mock_house_invitation(:save => false) }
        post :create, :house_invitation => {'these' => 'params'}
        assigns(:house_invitation).should be(mock_house_invitation)
      end

      it "re-renders the 'new' template" do
        HouseInvitation.stub(:new) { mock_house_invitation(:save => false) }
        post :create, :house_invitation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invitation" do
        HouseInvitation.stub(:find).with("37") { mock_house_invitation }
        mock_house_invitation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :house_invitation => {'these' => 'params'}
      end

      it "assigns the requested house_invitation as @house_invitation" do
        HouseInvitation.stub(:find) { mock_house_invitation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:house_invitation).should be(mock_house_invitation)
      end

      it "redirects to the invitation" do
        HouseInvitation.stub(:find) { mock_house_invitation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(invitation_url(mock_house_invitation))
      end
    end

    describe "with invalid params" do
      it "assigns the house_invitation as @house_invitation" do
        HouseInvitation.stub(:find) { mock_house_invitation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:house_invitation).should be(mock_house_invitation)
      end

      it "re-renders the 'edit' template" do
        HouseInvitation.stub(:find) { mock_house_invitation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invitation" do
      HouseInvitation.stub(:find).with("37") { mock_house_invitation }
      mock_house_invitation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the house_invitations list" do
      HouseInvitation.stub(:find) { mock_house_invitation }
      delete :destroy, :id => "1"
      response.should redirect_to(house_invitations_url)
    end
  end

end
