require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TascsController do

  def mock_tasc(stubs={})
    @mock_tasc ||= mock_model(Tasc, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tascs as @tascs" do
      Tasc.stub(:all) { [mock_tasc] }
      get :index
      assigns(:tascs).should eq([mock_tasc])
    end
  end

  describe "GET show" do
    it "assigns the requested tasc as @tasc" do
      Tasc.stub(:find).with("37") { mock_tasc }
      get :show, :id => "37"
      assigns(:tasc).should be(mock_tasc)
    end
  end

  describe "GET new" do
    it "assigns a new tasc as @tasc" do
      Tasc.stub(:new) { mock_tasc }
      get :new
      assigns(:tasc).should be(mock_tasc)
    end
  end

  describe "GET edit" do
    it "assigns the requested tasc as @tasc" do
      Tasc.stub(:find).with("37") { mock_tasc }
      get :edit, :id => "37"
      assigns(:tasc).should be(mock_tasc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tasc as @tasc" do
        Tasc.stub(:new).with({'these' => 'params'}) { mock_tasc(:save => true) }
        post :create, :tasc => {'these' => 'params'}
        assigns(:tasc).should be(mock_tasc)
      end

      it "redirects to the created tasc" do
        Tasc.stub(:new) { mock_tasc(:save => true) }
        post :create, :tasc => {}
        response.should redirect_to(tasc_url(mock_tasc))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tasc as @tasc" do
        Tasc.stub(:new).with({'these' => 'params'}) { mock_tasc(:save => false) }
        post :create, :tasc => {'these' => 'params'}
        assigns(:tasc).should be(mock_tasc)
      end

      it "re-renders the 'new' template" do
        Tasc.stub(:new) { mock_tasc(:save => false) }
        post :create, :tasc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tasc" do
        Tasc.stub(:find).with("37") { mock_tasc }
        mock_tasc.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tasc => {'these' => 'params'}
      end

      it "assigns the requested tasc as @tasc" do
        Tasc.stub(:find) { mock_tasc(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tasc).should be(mock_tasc)
      end

      it "redirects to the tasc" do
        Tasc.stub(:find) { mock_tasc(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tasc_url(mock_tasc))
      end
    end

    describe "with invalid params" do
      it "assigns the tasc as @tasc" do
        Tasc.stub(:find) { mock_tasc(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tasc).should be(mock_tasc)
      end

      it "re-renders the 'edit' template" do
        Tasc.stub(:find) { mock_tasc(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tasc" do
      Tasc.stub(:find).with("37") { mock_tasc }
      mock_tasc.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tascs list" do
      Tasc.stub(:find) { mock_tasc }
      delete :destroy, :id => "1"
      response.should redirect_to(tascs_url)
    end
  end

end
